#!/bin/bash

echo "🚀 Biblioteca - Deploy para Railway"
echo "===================================="
echo ""
echo "✅ Código já está no GitHub!"
echo "👉 Agora precisas fazer isto manualmente (1 minuto):"
echo ""
echo "1. Vai para https://railway.app"
echo "2. Faz login com GitHub (ou cria conta)"
echo "3. Clica 'New Project'"
echo "4. Escolhe 'Deploy from GitHub repo'"
echo "5. Autoriza Railway no GitHub"
echo "6. Seleciona 'FAALopes/Biblioteca'"
echo "7. Railway faz deploy automático! 🎉"
echo ""
echo "📍 O teu repositório GitHub está aqui:"
echo "   https://github.com/FAALopes/Biblioteca"
echo ""
echo "⏱️  Tempo estimado: 2 minutos até estar live!"
echo ""
